config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/welcome'

  resources :gifts
  resources :messages
  resources :events
  resources :contacts
  resources :users
  # resources :sessions 

  get 'login', to: 'sessions#new', as: 'new_session'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "pages#home", as: "home"



end

app/views/pages/grid-latout.html.erb
<%= button_to "Schedule an Event", new_event_path, method: :get %>

<%= button_to "Create New Contact", new_contact_path, method: :get %>

<div class="card p-4">
            <div class="card-body">
              <h3 class="text-center">Never forget or miss an important moment again.</h3>
              <hr>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="First Name">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Last Name">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Email">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Phone Number">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <textarea class="form-control" placeholder="Message"></textarea>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-outline-danger btn-block">
                  </div>
                </div>
              </div>
            </div>
          </div>

 <section id="contact" class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card p-4">
            <div class="card-body">
                <%@events.reverse_each do |event|%>
                  <img src="https://voidtech.net/images/calendar_color_picker/Calendar%20Color%20Picker%20Icon%20Large%20Clear.png" alt="" class="img-fluid card-img-top"> 
                  <hr>
                  <hr>
                  <h4 class="card-title"><%= link_to event.event_name, event_path(event) %></h4>
                  <small class="text-muted">Category: <%= event.category %></small>
                  <hr>
                  <small class="text-muted">Date: <%= event.date %></small>
                  <hr>
                  <small class="text-muted">Time: <%= event.time %></small>
                  <hr>
                  <p class="card-text">Message: <%= event.message %></p>
                  <hr>
                  <hr>
                <%end%>  
            </div>
          </div>
        </div>
       <div class="col-md-8">
          <div class="card p-4">
            <div class="card-body">
              <h3 class="text-center">Never forget or miss an important moment again.</h3>
              <hr>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="First Name">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Last Name">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Email">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Phone Number">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <textarea class="form-control" placeholder="Message"></textarea>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-outline-danger btn-block">
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
        
        
          
        
      </div>
    </div>
  </section>

app/views/pages/home.html.erb
<!--Our old code -->
<!--<h1>Forget Me Not</h1>
<br>

<h1>Add Logo</h1>

<h2>Organize, remind, and contact friends / loved ones of important events in their life, never forget or miss an important moment again.</h2>

Events Feed 




Our old code -->



    


<div class="card p-10">
            
                <div class="col-md-2">
                  <div class="form-group">
                
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
            <div class="description">
              <h1 class="text-center font-weight-normal">FRIEND SEND</h1>
            </div>
            
                <!-- 
                  <img class="img" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjGtIaF-6-Bz6jaxnTMWGjqLBEJ3PGgRDrsQ&usqp=CAU" alt="" class="img-fluid card-img-top" > 
                -->    
                  </div>
                </div>
              </div>
            </div>
          </div>



 <section id="contact" class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card p-4">
          <div class="event-feed"> 
          <h3 class="text-center"><%= link_to " EVENT FEED ", events_path, method: :get %></h3>
          </div>
            <div class="card-body">
                <%@events.reverse_each do |event|%>
                  <img src="https://www.pngkey.com/png/detail/24-243693_calendar-clock-icon-date-and-time-png.png" alt="" class="img-fluid card-img-top"> 
                  <hr>
                  <hr>
                  <h4 class="card-title"><%= link_to event.event_name, event_path(event) %></h4>
                  <small class="text-muted">Category: <%= event.category %></small>
                  <hr>
                  <small class="text-muted">Date: <%= event.date %></small>
                  <hr>
                  <small class="text-muted">Time: <%= event.time %></small>
                  <hr>
                  <p class="card-text">Message: <%= event.message %></p>
                  <hr>
                  <hr>
                <%end%>  
            </div>
          </div>
        </div>
       <div class="col-md-8">
          <div class="card p-4">
            <div class="card-body">
              <div class="subtitle">
              <h3 class="text-center font-weight-normal">Never miss an important moment again!</h3>
              <br>
              <hr>
              </div>
             
              <div class="row">
                <button class="btn btn-info" type="button"><h3 size: large;><%=link_to " Schedule an Event ", new_event_path, method: :get %></h3> </button>
                <hr>
                <button class="btn btn-info" type="button"><h3 size: large; ><%= link_to "Create New Contact", new_contact_path, method: :get %></h3></button>
                
              </div>
          </div>
        
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjGtIaF-6-Bz6jaxnTMWGjqLBEJ3PGgRDrsQ&usqp=CAU" alt="" class="img-fluid card-img-top"> 

              <hr>
          <div class="fmn-desc"> 
        
              <h5 class="text-center">With Friend Send you can create personalized message on your own time that will arrive on schedule. 
              Our CRM does the remebering for you!</h5>
  
          </div>
          </div>

        
      </div>
    </div>
  </section>
<!-- CONTACT SECTION -->'