config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/welcome'

  resources :gifts
  resources :messages
  resources :events
  resources :contacts
  resources :users
  # resources :sessions 

  get 'login', to: 'sessions#new', as: 'new_session'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "pages#home", as: "home"



end

app/views/layouts/_navbar.html.erb
<header>
    <div class= 'container'>
    <%= link_to home_path do %>
        <%= image_tag "forget-me-not-logo.jpg", class: "logo" %>
    <% end %>
        
        <nav> 
            <ul>
                 <% if @current_user %>
                    <li> <%= link_to "Home", home_path %></li>
                    <li> <%= link_to "Profile", user_path(@current_user) %></li>
                    <li> <%= link_to "Contacts", contacts_path %></li>
                    <li> <%= link_to "Events", events_path %></li>
                    <li><%= link_to "Logout", logout_path %></li>
                <% end %>
            </ul> 
        </nav>
    </div>
</header>

app/views/layouts/_nice_nav.html.erb
<header>
    <div class= 'container'>


<nav class="navbar navbar-expand-sm navbar-light bg-light mb-3">
        <div class="container">
             
            <a class="navbar-brand" href="#">
                <%= link_to home_path do %>
                    <h1 class="emoji" >✿</h1>
                <% end %>
            </a>
            
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                <% if @current_user %>
                    <li class="nav-item">
                        <%= link_to "Home", home_path%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Profile", user_path(@current_user) %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Contacts", contacts_path %>
                    </li>
                    <li class="nav-item">
                       <%= link_to "Events", events_path %>
                    </li>
                    <li class="nav-item">
                       <%= link_to "Logout", logout_path %>
                    </li>
                <% end %>
                </ul>
            </div>
        </div>
    </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
 <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Friend Send</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
   <%= render 'layouts/nice_nav' %>
  <%= yield %>
   
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>